### 載入工具

In [27]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [32]:
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
x = np.array(data)
print(x)
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(x)
print('\ninteger_encoded\n', integer_encoded)
integer_encoded = integer_encoded[:, np.newaxis]
print('\ninteger_encoded\n', integer_encoded)
onehot_encoder = OneHotEncoder(sparse=False, categories='auto')
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print('\nonehot_encoded\n', onehot_encoded)

inverted_onehot = onehot_encoder.inverse_transform([onehot_encoded[2]])
inverted_label = label_encoder.inverse_transform([np.argmax(onehot_encoded[2,:])])

print('\ninverted_onehot\n', inverted_onehot)
print('\ninverted_label\n', inverted_label)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']

integer_encoded
 [0 0 2 0 1 1 2 0 2 1]

integer_encoded
 [[0]
 [0]
 [2]
 [0]
 [1]
 [1]
 [2]
 [0]
 [2]
 [1]]

onehot_encoded
 [[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

inverted_onehot
 [[2]]

inverted_label
 ['warm']


In [41]:
onehot_encoded1 = np.array(onehot_encoded)
print(onehot_encoded1)
onehot_encoded2 = np.array(onehot_encoded)
print(onehot_encoded2)
onehot_stack = np.hstack((onehot_encoded1, onehot_encoded2))
print(onehot_stack)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]]
